name: Greetings

on:
  push:
    branches: [main]
  issues:
    types: [opened]
  pull_request_target:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: EddieHubCommunity/gh-action-community/src/welcome@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hello ${{ github.actor }}! Thanks for opening an issue in VedEats! 🚀 \n\n - We'll get back to you as soon as possible."
          pr-message: "Thank you, ${{ github.actor }}, for your contribution! Your pull request has been submitted successfully. A maintainer will review it as soon as possible. We appreciate your support in making VedEats better. 🎉 "